########
# Copyright (c) 2014 GigaSpaces Technologies Ltd. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
#    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    * See the License for the specific language governing permissions and
#    * limitations under the License.

# -*- mode: ruby -*-
# vi: set ft=ruby :

AWS_ACCESS_KEY_ID = ENV['AWS_ACCESS_KEY_ID']
AWS_ACCESS_KEY = ENV['AWS_ACCESS_KEY']
AWS_ACCESS_KEY_ID_UPLOAD_TEMP = ENV['AWS_ACCESS_KEY_ID_UPLOAD_TEMP']
AWS_ACCESS_KEY_UPLOAD_TEMP = ENV['AWS_ACCESS_KEY_UPLOAD_TEMP']
GITHUB_USERNAME = ENV['GITHUB_USERNAME']
GITHUB_PASSWORD = ENV['GITHUB_PASSWORD']
PLUGIN_NAME = ENV['PLUGIN_NAME']


CENTOS_FINAL_BOX_NAME = 'chef/centos-6.5'
CENTOS7_OFFICIAL_BOX_URL = 'http://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7.box'


Vagrant.configure('2') do |config|
  config.vm.define "centos_core_plugin_wheel" do |centos_core|
    #dummy box, will be overriden
    centos_core.vm.box = "dummy"
    centos_core.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
    centos_core.vm.provider :aws do |aws, override|
      aws.access_key_id = AWS_ACCESS_KEY_ID
      aws.secret_access_key = AWS_ACCESS_KEY
      aws.ami = "ami-fd69068a"
      aws.region = "eu-west-1"
      aws.instance_type = "m3.medium"
      aws.keypair_name = "vagrant_build"
      override.ssh.username = "ec2-user"
      override.ssh.private_key_path = "~/.ssh/aws/vagrant_build.pem"
      override.nfs.functional = false
      aws.tags = { "Name" => "vagrant plugin centos 7.0 build" }
      aws.security_groups = "vagrant_linux_build"
    end
    centos_core.vm.synced_folder "../../", "/wagon", create: true
    centos_core.vm.provision "shell" do |s|
      s.path = "provision.sh"
      s.args = "#{GITHUB_USERNAME} #{GITHUB_PASSWORD} #{AWS_ACCESS_KEY_ID} #{AWS_ACCESS_KEY} #{PLUGIN_NAME}"
      s.privileged = false
    end
  end

end
